name: Fork and Upload

on:
  workflow_dispatch: # Manual trigger

jobs:
  fork_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone source repository
        run: |
          git clone --depth=10 https://github.com/aircrack-ng/rtl8188eus.git upstream-repo

      - name: Copy contents to current repo
        run: |
          rsync -av --exclude='.git' upstream-repo/ ./

      - name: Set up git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Forked from upstream"
          git push
