name: Upstream Sync

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Upstream repository (owner/repo)'
        required: true
        default: 'ORIGINAL_OWNER/ORIGINAL_REPO'
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get upstream repository
      id: upstream
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "repo=${{ github.event.inputs.upstream_repo }}" >> $GITHUB_OUTPUT
        else
          echo "repo=ORIGINAL_OWNER/ORIGINAL_REPO" >> $GITHUB_OUTPUT
        fi

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/${{ steps.upstream.outputs.repo }}.git

    - name: Fetch upstream
      run: |
        git fetch upstream

    - name: Check for updates
      id: check
      run: |
        if git log HEAD..upstream/main --oneline; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
        fi

    - name: Merge updates
      if: steps.check.outputs.has_updates == 'true'
      run: |
        git merge upstream/main --no-edit

    - name: Push changes
      if: steps.check.outputs.has_updates == 'true'
      run: |
        git push origin HEAD:${{ github.ref }}
