name: Mirror Repository

on:
  schedule:
    # Run every 1 am
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        
    - name: Mirror from target repository
      run: |
        # Add target repository as remote
        git remote add target https://github.com/BlackArch/blackarch.git
        
        # Fetch all branches and tags from target
        git fetch target --tags
        
        # Push all branches to current repository
        git push --all origin
        
        # Push all tags to current repository
        git push --tags origin
      env:
        # Use a personal access token for write access
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
