name: Clone and Upload Repository

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository URL'
        required: true
        default: 'https://github.com/Significant-Gravitas/AutoGPT.git'
      github_token:
        description: 'GitHub token'
        required: true
        default: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  clone-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        fetch-depth: 0

    - name: Clone source repository
      run: |
        git clone --mirror ${{ github.event.inputs.source_repo }} source-repo-mirror

    - name: Add source as remote and fetch
      run: |
        cd source-repo-mirror
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git push --mirror
