name: Sync Fork

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # disable default credentials so we set our own

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          # 👉 Replace with the source repo you want to mirror
          git remote add upstream https://github.com/Significant-Gravitas/AutoGPT.git
          git fetch upstream --prune

      - name: Sync master branch
        run: |
          git checkout master
          git merge --ff-only upstream/master || true

      - name: Push changes (skip upstream workflows)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          # Remove any upstream workflow updates
          git reset HEAD
          git restore --staged .
          git add --all ':!*.github/workflows/*'
          git commit -m "Sync upstream (without workflows)" || echo "No non-workflow changes"
          git push origin master

      - name: Sync all other branches and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch upstream --tags
          for branch in $(git branch -r | grep upstream/ | grep -v upstream/master | sed 's|upstream/||'); do
            git checkout -B $branch upstream/$branch
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push origin $branch
          done
          git push origin --tags
