name: Daily Fork Sync

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Significant-Gravitas/AutoGPT.git
          git fetch upstream || echo "Upstream fetch failed"

      - name: Find current branch
        id: branch
        run: |
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Pull upstream changes
        run: |
          set -e
          # If upstream branch exists, pull; else, skip
          if git ls-remote --exit-code --heads upstream $(git rev-parse --abbrev-ref HEAD); then
            git pull upstream $(git rev-parse --abbrev-ref HEAD) --no-edit
            git push origin $(git rev-parse --abbrev-ref HEAD)
          else
            echo "Upstream branch $(git rev-parse --abbrev-ref HEAD) does not exist, skipping."
          fi
