name: Fork and Sync Repository

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository (owner/repo)'
        required: true
        default: 'owner/source-repo'
      github_token:
        description: 'GitHub token with repo permissions'
        required: true
        default: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  fork-and-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add target repository as remote
      run: |
        git remote add target https://github.com/${{ github.event.inputs.target_repo }}.git
        git fetch target --tags

    - name: Get all branches from target
      run: |
        for branch in $(git branch -r | grep target/ | sed 's/target\///' | grep -v 'HEAD'); do
          git checkout -b $branch target/$branch || true
        done

    - name: Push all branches to current repository
      run: |
        git push origin --all --force
        git push origin --tags --force
