name: Sync Fork

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use our own token

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          # Replace with the repository you want to fork/sync from
          git remote add upstream https://github.com/Significant-Gravitas/AutoGPT.git
          git fetch upstream --prune

      - name: Sync default branch
        run: |
          # Replace 'main' with the source repository’s default branch if different
          git checkout master
          git merge --ff-only upstream/master || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main

      - name: Sync all branches and tags
        run: |
          git fetch upstream --tags
          for branch in $(git branch -r | grep upstream/ | grep -v upstream/main | sed 's|upstream/||'); do
            git checkout -B $branch upstream/$branch
            git push origin $branch
          done
          git push origin --tags
